"""
Generic ToolDefinition and ToolScenario.

A ToolDefinition describes a single external tool the agent can interact with
(e.g. Weather, GitHub, Database). A ToolScenario describes a specific version
of that tool's contract, plus a safe simulator function that produces a
response matching that contract.

IMPORTANT: Simulators are always plain Python callables defined in this
codebase. They are never generated by the LLM. The LLM only reasons about
the contract; execution happens through these approved simulators.
"""

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Optional


@dataclass
class ToolScenario:
    """One version of a tool's environment (e.g. Weather v1)."""
    version: str
    endpoint: str
    method: str
    contract: Dict[str, Any]
    simulate: Callable[[], Dict[str, Any]]
    description: str = ""


@dataclass
class ToolDefinition:
    """A tool the agent can adapt to."""
    name: str                          # e.g. "weather"
    display_name: str                  # e.g. "Weather API"
    description: str
    scenarios: Dict[str, ToolScenario] = field(default_factory=dict)
    default_version: str = "v1"
    _active_version: Optional[str] = None

    def __post_init__(self):
        if self._active_version is None:
            self._active_version = self.default_version

    @property
    def active_version(self) -> str:
        return self._active_version

    @property
    def active_scenario(self) -> ToolScenario:
        return self.scenarios[self._active_version]

    def get_scenario(self, version: str) -> ToolScenario:
        if version not in self.scenarios:
            raise ValueError(
                f"Tool '{self.name}' has no scenario '{version}'. "
                f"Available: {list(self.scenarios.keys())}"
            )
        return self.scenarios[version]

    def activate(self, version: str) -> ToolScenario:
        if version not in self.scenarios:
            raise ValueError(
                f"Cannot activate unknown scenario '{version}' for tool '{self.name}'."
            )
        self._active_version = version
        return self.scenarios[version]

    def to_dict(self) -> Dict[str, Any]:
        """Safe JSON representation for API responses."""
        return {
            "name": self.name,
            "display_name": self.display_name,
            "description": self.description,
            "default_version": self.default_version,
            "active_version": self.active_version,
            "scenarios": {
                v: {
                    "version": s.version,
                    "endpoint": s.endpoint,
                    "method": s.method,
                    "contract": s.contract,
                    "description": s.description,
                }
                for v, s in self.scenarios.items()
            },
        }
